mysql.exe -h localhost -u lib librusec <0.sql
mysql.exe -h localhost -u lib librusec <1.sql
mysql.exe -h localhost -u lib librusec <2.sql
mysql.exe -h localhost -u lib librusec <3.sql
mysql.exe -h localhost -u lib librusec <4.sql
mysql.exe -h localhost -u lib librusec <5.sql
mysql.exe -h localhost -u lib librusec <6.sql
mysql.exe -h localhost -u lib librusec <7.sql
mysql.exe -h localhost -u lib librusec <8.sql
